ExpenseManager/ExpenseManager/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;

namespace ExpenseManager.Controllers
{
    public class SalaryController : Controller
    {
        private readonly Contexto _context;

        public SalaryController(Contexto context)
        {
            _context = context;
        }

        // GET: Salary
        public async Task<IActionResult> Index()
        {
            var contexto = _context.Salaries.Include(s => s.Months);
            return View(await contexto.ToListAsync());
        }

        

        // GET: Salary/Create
        public IActionResult Create()
        {
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId != s.Salary.MonthId), "MonthId", "Name");
            return View();
        }

        // POST: Salary/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SalaryId,MonthId,Value")] Salary salary)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirm"] = "Salary registered with success";
                _context.Add(salary);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId != s.Salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

        // GET: Salary/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var salary = await _context.Salaries.FindAsync(id);
            if (salary == null)
            {
                return NotFound();
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId == salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

        // POST: Salary/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SalaryId,MonthId,Value")] Salary salary)
        {
            if (id != salary.SalaryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(salary);
                    await _context.SaveChangesAsync();
                    TempData["Confirm"] = "Salary updated with success";
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SalaryExists(salary.SalaryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MonthId"] = new SelectList(_context.Months.Where(s => s.MonthId == salary.MonthId), "MonthId", "Name", salary.MonthId);
            return View(salary);
        }

      


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var salary = await _context.Salaries.FindAsync(id);
            _context.Salaries.Remove(salary);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SalaryExists(int id)
        {
            return _context.Salaries.Any(e => e.SalaryId == id);
        }
    }
}

ExpenseManager/ExpenseManager/Controllers/TypeExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseManager.Models;

namespace ExpenseManager.Controllers
{
    public class TypeExpensesController : Controller
    {
        private readonly Contexto _context;

        public TypeExpensesController(Contexto context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _context.TypeExpenses.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> Index(string txtProcurar)
        {
            if (!string.IsNullOrEmpty(txtProcurar))
                return View(await _context.TypeExpenses.Where(te => te.Name.ToUpper().Contains(txtProcurar.ToUpper())).ToListAsync());

            return View(await _context.TypeExpenses.ToListAsync());
        }
        public async Task<JsonResult> TypeExpenseExists(string name)
        {
            if (await _context.TypeExpenses.AnyAsync(te => te.Name.ToUpper() == name.ToUpper()))
            {
                return Json("Esse tipo de despesa já existe!");
            }
            return Json(true);
        }
       
        // GET: TypeExpenses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TypeExpenses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TypeExpenseId,Name")] TypeExpense typeExpense)
        {
            if (ModelState.IsValid)
            {
                TempData["Confirm"] = typeExpense.Name + " has been successfully registered.";
                _context.Add(typeExpense);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(typeExpense);
        }

        // GET: TypeExpenses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var typeExpense = await _context.TypeExpenses.FindAsync(id);
            if (typeExpense == null)
            {
                return NotFound();
            }
            return View(typeExpense);
        }

        // POST: TypeExpenses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TypeExpenseId,Name")] TypeExpense typeExpense)
        {
            if (id != typeExpense.TypeExpenseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    TempData["Confirm"] = typeExpense.Name + " has been successfully updated.";
                    _context.Update(typeExpense);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TypeExpenseExists(typeExpense.TypeExpenseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(typeExpense);
        }

        //// GET: TypeExpenses/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var typeExpense = await _context.TypeExpenses
        //        .FirstOrDefaultAsync(m => m.TypeExpenseId == id);
        //    if (typeExpense == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(typeExpense);
        //}

        // POST: TypeExpenses/Delete/5
        [HttpPost]
        public async Task<JsonResult> Delete(int id)
        {
            var typeExpense = await _context.TypeExpenses.FindAsync(id);
            TempData["Confirm"] = typeExpense.Name + " has been successfully deleted.";
            _context.TypeExpenses.Remove(typeExpense);
            await _context.SaveChangesAsync();
            return Json(typeExpense.Name + "Deleted.");
        }

        private bool TypeExpenseExists(int id)
        {
            return _context.TypeExpenses.Any(e => e.TypeExpenseId == id);
        }
    }
}

ExpenseManager/ExpenseManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Expense Manager</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Expense Manager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">Expense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TypeExpenses" asp-action="Index">Type Expense</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Salary" asp-action="Index">Income</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ExpenseManager
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>